
services:

  dns-platform:
    container_name: dns-platform
    build:
      context: .
      dockerfile: Dockerfile
    image: dns-platform
    ports:
      - 8053:80
      - 5053:53/udp
      - 5053:53/tcp
    environment:
      - TZ=Europe/Madrid
      - ROOT_DOMAIN=example.com.
    volumes:
      - .:/code
      - dns-platform-bind:/etc/bind

volumes:
  dns-platform-bind:
